import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'introduction',
    'learning-outcomes',
    'hardware-requirements',
    {
      type: 'category',
      label: 'Assessments',
      items: [
        'assessments/introduction',
        'assessments/assessment-1-ros',
        'assessments/assessment-2-gazebo',
        'assessments/assessment-3-isaac',
        'assessments/assessment-4-capstone',
      ],
    },
    {
      type: 'category',
      label: 'Part 1: Foundations',
      items: [{type: 'autogenerated', dirName: 'part1-foundations'}],
    },
    {
      type: 'category',
      label: 'Part 2: Core Tooling',
      items: [
        {
          type: 'category',
          label: 'ROS 2 Fundamentals',
          items: [{type: 'autogenerated', dirName: 'part2-core-tooling/ros-fundamentals'}],
        },
        {
          type: 'category',
          label: 'Gazebo Simulation',
          items: [{type: 'autogenerated', dirName: 'part2-core-tooling/gazebo'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Part 3: Advanced AI',
      items: [
        {
          type: 'category',
          label: 'NVIDIA Isaac Platform',
          items: [{type: 'autogenerated', dirName: 'part3-advanced-ai/isaac-platform'}],
        },
        {
          type: 'category',
          label: 'Humanoid Robot Development',
          items: [{type: 'autogenerated', dirName: 'part3-advanced-ai/humanoid-development'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Part 4: Capstone',
      items: [
        {
          type: 'category',
          label: 'Conversational Robotics',
          items: [{type: 'autogenerated', dirName: 'part4-capstone/conversational-robotics'}],
        },
      ],
    },
  ],
};

export default sidebars;
